import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { patientApi } from '../../api/patientApi';
import { scheduleApi } from '../../api/scheduleApi';
import { billingApi } from '../../api/billingApi';
import PageHeader from '../../components/common/PageHeader';
import EmptyState from '../../components/common/EmptyState';
import StatusBadge from '../../components/ui/StatusBadge';
import PatientBioPanel from '../../components/common/PatientBioPanel';
import { dateOnly, money, personName } from '../../utils/format';

export default function BillerDashboard(){
  const [patients,setPatients]=useState([]); const [schedules,setSchedules]=useState([]); const [claims,setClaims]=useState([]); const [active,setActive]=useState(null); const [insurance,setInsurance]=useState({approvalStatus:'approved',approvalReference:'',approvalValidFrom:new Date().toISOString().slice(0,10),approvalValidTo:'2026-12-31'});
  const load=async()=>{try{const [p,s,c]=await Promise.allSettled([patientApi.list(),scheduleApi.list(),billingApi.listClaims()]); if(p.status==='fulfilled') setPatients(p.value.data?.data||[]); if(s.status==='fulfilled') setSchedules(s.value.data?.schedules||[]); if(c.status==='fulfilled') setClaims(c.value.data?.data||[]);}catch(e){toast.error(e?.response?.data?.message||'Failed to load biller dashboard')}};
  useEffect(()=>{load()},[]);
  const insuranceQueue=useMemo(()=>patients.filter((p)=>p.sentToBillerAt || p.insurance?.approvalStatus!=='approved'),[patients]);
  const updateInsurance=async(p)=>{try{await billingApi.updateInsurance(p.mrn||p._id,{...p.insurance,...insurance}); toast.success('Insurance updated'); setActive(null); load();}catch(e){toast.error(e?.response?.data?.message||'Failed to update insurance')}};
  const paymentForSchedule=(s)=>claims.find((c)=>c.session?.schedule===s.id || c.patient?.mrn===s.patientMrn);
  return <div className="space-y-5"><PageHeader title="Biller Dashboard" subtitle="Insurance verification queue, all schedules payment status, claims and payment follow-up." />
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{['pending','submitted','paid','denied','partial'].map((s)=><div className="card p-4" key={s}><p className="text-xs uppercase text-slate-500">{s}</p><p className="text-2xl font-bold">{claims.filter((c)=>c.status===s).length}</p></div>)}</div>
    <section className="card p-5"><h2 className="mb-3 font-bold">Insurance Verification Queue</h2><div className="space-y-2">{insuranceQueue.map((p)=><div className="rounded-xl border p-3 text-sm" key={p._id}><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><b>{personName(p)}</b><p className="text-xs text-slate-500">{p.mrn} • {p.phone} • {p.address}</p><p className="text-xs text-slate-500">{p.insurance?.providerName||'-'} • Member {p.insurance?.memberId||'-'} • Policy {p.insurance?.policyNumber||'-'}</p><p className="text-xs text-slate-500">Plan {p.insurance?.planType||'-'} • Transport {p.insurance?.transportationBenefits||'-'}</p></div><div className="flex items-center gap-2"><StatusBadge status={p.insurance?.approvalStatus||'not_submitted'} /><button className="btn-light" onClick={()=>{setActive(p); setInsurance({approvalStatus:p.insurance?.approvalStatus||'approved',approvalReference:p.insurance?.approvalReference||`APP-${Date.now()}`,approvalValidFrom:dateOnly(p.insurance?.approvalValidFrom)||new Date().toISOString().slice(0,10),approvalValidTo:dateOnly(p.insurance?.approvalValidTo)||'2026-12-31'});}}>Review</button></div></div>{active?._id===p._id&&<div className="mt-3 space-y-3"><PatientBioPanel patient={p} claims={claims.filter((c)=>(c.patient?._id||c.patient)===p._id || c.patient?.mrn===p.mrn)} compact={false}/><div className="grid gap-3 md:grid-cols-5"><select className="input" value={insurance.approvalStatus} onChange={(e)=>setInsurance({...insurance,approvalStatus:e.target.value,coverageStatus:e.target.value})}>{['submitted','approved','rejected','expired','not_submitted'].map(x=><option key={x}>{x}</option>)}</select><input className="input" value={insurance.approvalReference} onChange={(e)=>setInsurance({...insurance,approvalReference:e.target.value})} placeholder="Approval Ref"/><input className="input" type="date" value={insurance.approvalValidFrom} onChange={(e)=>setInsurance({...insurance,approvalValidFrom:e.target.value})}/><input className="input" type="date" value={insurance.approvalValidTo} onChange={(e)=>setInsurance({...insurance,approvalValidTo:e.target.value})}/><button className="btn-primary" onClick={()=>updateInsurance(p)}>Save</button></div></div>}</div>)}{!insuranceQueue.length&&<EmptyState message="No insurance pending"/>}</div></section>
    <section className="card overflow-x-auto"><div className="p-5"><h2 className="font-bold">All Schedules Payment View</h2></div><table className="w-full text-sm"><thead><tr className="border-y bg-slate-50 text-left"><th className="p-3">Patient</th><th>Date/Time</th><th>Chair</th><th>Insurance</th><th>Payment</th><th>Amount</th></tr></thead><tbody>{schedules.map((s)=>{const p=patients.find(x=>x.mrn===s.patientMrn); const cl=paymentForSchedule(s); return <tr className="border-b" key={s.id}><td className="p-3"><b>{s.patientName}</b><br/><span className="text-xs text-slate-500">{s.patientMrn}</span></td><td>{dateOnly(s.date)}<br/><span className="text-xs text-slate-500">{s.startTime}-{s.endTime}</span></td><td>{s.chair?.code}</td><td><StatusBadge status={p?.insurance?.approvalStatus||'not_submitted'}/></td><td><StatusBadge status={cl?.status||'unpaid'}/></td><td>{money(cl?.amount||0)}</td></tr>})}</tbody></table></section>
  </div>
}
