import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { sessionApi } from '../../api/sessionApi';
import StatusBadge from '../../components/ui/StatusBadge';
import PageHeader from '../../components/common/PageHeader';
import EmptyState from '../../components/common/EmptyState';
import { dateOnly, personName } from '../../utils/format';
import Pagination, { usePagedList } from '../../components/common/Pagination';

const blankVitals = { phase: 'before', bloodPressure: '', heartRate: '', temperature: '', weight: '', spo2: '' };
const blankSoap = { subjective: '', objective: '', assessment: '', plan: '' };

export default function SessionList() {
  const [items, setItems] = useState([]);
  const [filters, setFilters] = useState({ status: '', patient: '', schedule: '' });
  const [active, setActive] = useState(null);
  const [search, setSearch] = useState('');
  const [vitals, setVitals] = useState(blankVitals);
  const [soap, setSoap] = useState(blankSoap);
  const [summary, setSummary] = useState('Dialysis completed successfully without complications.');
  const params = Object.fromEntries(Object.entries(filters).filter(([, v]) => v));
  const { paged, page, setPage, total, pageCount } = usePagedList(items, search, [(x) => personName(x.patient), (x) => x._id]);

  const load = async () => { try { const res = await sessionApi.list(params); setItems(res.data?.data || []); } catch (e) { toast.error(e?.response?.data?.message || 'Failed to load sessions'); } };
  useEffect(() => { load(); }, []);
  const act = async (message, fn) => { try { await fn(); toast.success(message); setActive(null); load(); } catch (e) { toast.error(e?.response?.data?.message || 'Action failed'); } };

  return <div className="space-y-4"><PageHeader title="Dialysis Sessions" subtitle="Check-in, start treatment, record vitals/SOAP, complete treatment and maintain history." />
    <div className="card grid gap-3 p-4 md:grid-cols-6"><select className="input" value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">All Status</option>{['scheduled','ready','checked_in','in_progress','completed','cancelled','no_show'].map((s) => <option key={s}>{s}</option>)}</select><input className="input md:col-span-2" placeholder="Patient ID" value={filters.patient} onChange={(e) => setFilters({ ...filters, patient: e.target.value })} /><input className="input" placeholder="Schedule ID" value={filters.schedule} onChange={(e) => setFilters({ ...filters, schedule: e.target.value })} /><input className="input" placeholder="Search patient" value={search} onChange={(e) => setSearch(e.target.value)} /><button className="btn-light" onClick={load}>Filter</button></div>
    <div className="space-y-3">{paged.map((session) => <div className="card p-4" key={session._id}><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><b>{personName(session.patient)}</b><p className="text-sm text-slate-500">Chair {session.chair?.code || session.chair?.chairNumber || session.chair} • Schedule {session.schedule?.code || session.schedule?._id || session.schedule}</p><p className="text-xs text-slate-400">Session: {session._id} • Created {dateOnly(session.createdAt)}</p></div><StatusBadge status={session.status} /></div><div className="mt-4 flex flex-wrap gap-2"><button className="btn-light" disabled={!['scheduled','ready'].includes(session.status)} onClick={() => act('Patient checked in', () => sessionApi.checkIn(session._id))}>Check In</button><button className="btn-light" disabled={!['checked_in','ready'].includes(session.status)} onClick={() => act('Session started', () => sessionApi.start(session._id))}>Start</button><button className="btn-light" disabled={!['in_progress','completed'].includes(session.status)} onClick={() => { setActive({ type: 'vitals', session }); setVitals({ ...blankVitals, phase: 'before' }); }}>Add Vitals</button><button className="btn-light" disabled={!['in_progress','completed'].includes(session.status)} onClick={() => { setActive({ type: 'soap', session }); setSoap(blankSoap); }}>SOAP</button><button className="btn-primary" disabled={session.status !== 'in_progress'} title={session.status !== 'in_progress' ? 'Session must be in_progress before complete' : ''} onClick={() => { setActive({ type: 'complete', session }); setSummary('Dialysis completed successfully without complications.'); }}>Complete</button></div><div className="mt-3 grid gap-2 text-xs text-slate-500 md:grid-cols-3"><div>Vitals: {session.vitals?.length || 0}</div><div>SOAP: {session.soapNotes?.length || 0}</div><div>Completed: {dateOnly(session.completedAt)}</div></div><div className="mt-3 grid gap-3 lg:grid-cols-2"><div className="rounded-xl border p-3 text-xs"><b>Vitals History</b><div className="mt-2 space-y-1">{(session.vitals || []).map((v) => <p key={v._id || `${v.phase}-${v.recordedAt}`}><span className="capitalize font-semibold">{v.phase}</span> • BP {v.bloodPressure || '-'} • HR {v.heartRate || '-'} • Temp {v.temperature || '-'}</p>)}{!(session.vitals || []).length && <p className="text-slate-400">No vitals yet</p>}</div></div><div className="rounded-xl border p-3 text-xs"><b>SOAP History</b><div className="mt-2 space-y-1">{(session.soapNotes || []).map((n, i) => <p key={i}>S: {n.subjective || '-'} / A: {n.assessment || '-'}</p>)}{!(session.soapNotes || []).length && <p className="text-slate-400">No SOAP yet</p>}</div></div></div></div>)}{items.length === 0 && <EmptyState message="No sessions found" />}<Pagination page={page} pageCount={pageCount} total={total} onPage={setPage} label="sessions" /></div>
    {active && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="card max-h-[90vh] w-full max-w-2xl overflow-y-auto p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">{active.type === 'vitals' ? 'Add Vitals' : active.type === 'soap' ? 'Add SOAP Notes' : 'Complete Session'}</h2><button className="btn-light" onClick={() => setActive(null)}>Close</button></div>{active.type === 'vitals' && <div className="grid gap-3 md:grid-cols-2"><select className="input" value={vitals.phase} onChange={(e) => setVitals({ ...vitals, phase: e.target.value })}><option value="before">before</option><option value="during">during</option><option value="after">after</option></select><input className="input" placeholder="Blood pressure" value={vitals.bloodPressure} onChange={(e) => setVitals({ ...vitals, bloodPressure: e.target.value })} /><input className="input" placeholder="Heart rate" type="number" value={vitals.heartRate} onChange={(e) => setVitals({ ...vitals, heartRate: e.target.value })} /><input className="input" placeholder="Temperature" type="number" step="0.1" value={vitals.temperature} onChange={(e) => setVitals({ ...vitals, temperature: e.target.value })} /><input className="input" placeholder="Weight" type="number" value={vitals.weight} onChange={(e) => setVitals({ ...vitals, weight: e.target.value })} /><input className="input" placeholder="SPO2" type="number" value={vitals.spo2} onChange={(e) => setVitals({ ...vitals, spo2: e.target.value })} /><button className="btn-primary md:col-span-2" onClick={() => act('Vitals added', () => sessionApi.vitals(active.session._id, { ...vitals, heartRate: Number(vitals.heartRate), temperature: Number(vitals.temperature), weight: Number(vitals.weight), spo2: Number(vitals.spo2) }))}>Save Vitals</button></div>}{active.type === 'soap' && <div className="space-y-3">{Object.keys(soap).map((k) => <textarea key={k} className="input min-h-20" placeholder={k} value={soap[k]} onChange={(e) => setSoap({ ...soap, [k]: e.target.value })} />)}<button className="btn-primary" onClick={() => act('SOAP saved', () => sessionApi.soap(active.session._id, soap))}>Save SOAP</button></div>}{active.type === 'complete' && <div className="space-y-3"><textarea className="input min-h-28" value={summary} onChange={(e) => setSummary(e.target.value)} /><button className="btn-primary" onClick={() => act('Session completed', () => sessionApi.complete(active.session._id, { treatmentSummary: summary }))}>Complete Session</button></div>}</div></div>}
  </div>;
}
